config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab_3/', include('lab_3.urls')),
    path('lab_4/', include('lab_4.urls')),
]

lab_3/urls.py
from django.urls import path
from .views import password_view
from .views import main_page, toggle_theme


urlpatterns = [
    path('password/', password_view, name='password_view'),
    path('main/', main_page, name='main_page'),
    path('main/toggle-theme/', toggle_theme, name='toggle_theme'),
]

lab_4/urls.py
from django.urls import path
from .views import sport_view, upload_file, file_list, sportperson_list, get_sportperson, find_sportperson, edit_sp_temp, edit_sportperson, delete_sportperson

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('mainsport/', sport_view, name='sport_view'),
        path('upload/', upload_file, name='upload_file'),
        path('files/', file_list, name='file_list'),
        path('sportsperson/', sportperson_list, name='splist'),
        path('get_sportperson/', get_sportperson, name='get_sportperson'),
        path('find_sportperson/', find_sportperson, name='find_sportperson'),
        path('edit_sportperson/', edit_sportperson, name='edit_sportperson'),
        path('edit_sp_temp/', edit_sp_temp, name='edit_sp_temp'),
        path('delete_sportperson/', delete_sportperson, name='delete_sportperson'),
    ]
if settings.DEBUG: #во время разработки мы получаем новый маршрут: /localhost8000/media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab_4/models.py
from django.db import models

class Document(models.Model): #модель, определяющая то, какой информацией будет сопровождаться загруженный документ
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='documents/')  # Путь, куда сохраняются файлы
    uploaded_at = models.DateTimeField(auto_now_add=True)
# Create your models here.

class Sportspeople(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=100)
    spcat = models.CharField(max_length=100)
    sptype = models.TextField()  # Используем TextField для хранения нескольких значений
#    savepl = models.CharField(max_length=100)  # Добавляем поле для хранения места сохранения
    class Meta:
        unique_together = ('name', 'surname', 'age', 'gender', 'spcat', 'sptype')

lab_4/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Document, Sportspeople
import json

SPORT_CATEGORIES = [
    ('candidate', 'Кандидат в мастера спорта'),
    ('first', 'Первый спортивный разряд'),
    ('second', 'Второй спортивный разряд'),
    ('third', 'Третий спортивный разряд'),
    ('junior_first', 'Первый юношеский спортивный разряд'),
    ('junior_second', 'Второй юношеский спортивный разряд'),
    ('junior_third', 'Третий юношеский спортивный разряд')
]
GENDERS = [('man', 'Мужчина'), ('woman', 'Женщина')]
SPORT_TYPES = [
    ('hockey', 'Хоккей'),
    ('football', 'Футбол'),
    ('skating', 'Фигруное катание'),
    ('biathlon', 'Биатлон'),
    ('boxing', 'Бокс'),
    ('other', 'Другое'),
]
SAVINGPLACE = [(1, 'JSON'), (2, 'DB')]

class SportForm(forms.ModelForm):
    class Meta:
        model = Sportspeople
        fields = ['name', 'surname', 'age', 'gender', 'spcat', 'sptype']#'savepl'

    name = forms.CharField(widget=forms.TextInput, label="Имя")
    surname = forms.CharField(widget=forms.TextInput, label="Фамилия")
    age = forms.IntegerField(widget=forms.Textarea(attrs={'rows': 1, 'cols': 10}), label="Возраст", min_value=1, max_value=100)
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDERS, label="Пол")
    spcat = forms.ChoiceField(choices=SPORT_CATEGORIES, label="Спортивная категория")
    sptype = forms.MultipleChoiceField(
        required=True,
        widget=forms.CheckboxSelectMultiple,
        choices=SPORT_TYPES,
        label="Виды спорта"
    )
    savepl = forms.ChoiceField(choices=SAVINGPLACE, label="Сохранить в...")
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        surname = cleaned_data.get('surname')
        age = cleaned_data.get('age')
        gender = cleaned_data.get('gender')
        spcat = cleaned_data.get('spcat')
        sptype = cleaned_data.get('sptype')

        # Преобразуем список sptype в строку, разделенную запятыми
        sptype = ",".join(sorted(sptype))  # Строка типов спорта для поиска дубликатов

        # Проверяем наличие дубликата в базе данных
        if Sportspeople.objects.filter(
            name=name, 
            surname=surname, 
            age=age, 
            gender=gender, 
            spcat=spcat, 
            sptype=sptype
            ).exists():
            raise ValidationError("Спортсмен с такими данными уже существует.")
        return cleaned_data

READINGPLACE = [(1, 'JSON'), (2, 'DB')]

class SportListForm(forms.Form):
    readpl = forms.ChoiceField(choices=READINGPLACE, label="Прочитать из...")

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('file',)

    def clean_file(self):
        file = self.cleaned_data.get('file')
        print(file.name)
        # Проверяем расширение файла
        if not file.name.endswith('.json'):
            raise forms.ValidationError('Только файлы формата JSON допустимы.')
        try:
            # Читаем файл для проверки на JSON
            file_content = file.read().decode('utf-8')
            json.loads(file_content)
            file.seek(0)  # Возвращаем курсор в начало для последующего использования
        except (json.JSONDecodeError, UnicodeDecodeError):
            raise forms.ValidationError('Файл не является валидным JSON.')
        return file

#def clean_file(self):
#     file = self.cleaned_data.get('file')
#     mime = magic.Magic(mime=True)
#     file_type = mime.from_buffer(file.read())
#     if not file_type.startswith('image/'):  # Например, только изображения
#         raise forms.ValidationError('Этот файл не является изображением.')
#     return file

lab_4/views.py
from django.http import HttpResponse
from .forms import SportForm
from .forms import DocumentForm, SportListForm, GENDERS, SPORT_CATEGORIES, SPORT_TYPES
from django.shortcuts import render, redirect, get_object_or_404
from .models import Document, Sportspeople
from django.conf import settings
import os
import json
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest
from django.db import IntegrityError


def sport_view(request):
    if request.method == 'POST':
        form = SportForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data 
            savepl = data.pop('savepl')  # извлекает и удаляет значения с ключами 'savepl' из формы
            if savepl == '1':
                save_sportspeople_data(data)
                messages.success(request, 'Данные успешно сохранены в JSON файл.')  # Добавлено сообщение об успешном сохранении
                form = SportForm()  # Создаем новый экземпляр формы
                return render(request, 'lab_4/main.html', {'form': form})
            elif savepl == '2':
                name = data['name']
                surname = data['surname']
                age = data['age']
                gender = dict(GENDERS).get(data['gender'], data['gender'])#добавляем не ключи, а значения
                spcat = dict(SPORT_CATEGORIES).get(data['spcat'])
                sptype = ', '.join([dict(SPORT_TYPES).get(sptype) for sptype in data['sptype']]) #через запятую выводим значения, а не ключи
                sportsperson = Sportspeople(name=name, surname=surname, age=age, gender=gender, spcat=spcat, sptype=sptype)
                try:
                    sportsperson.save()
                except IntegrityError:
                    messages.error(request, 'Обнаружен дупликат')
                    return render(request, 'lab_4/main.html', {'form': form})
                messages.success(request, 'Данные успешно сохранены в базу данных.')  # Добавлено сообщение об успешном сохранении
                form = SportForm()  # Создаем новый экземпляр формы
                return render(request, 'lab_4/main.html', {'form': form})
    else:
        form = SportForm()  
    return render(request, 'lab_4/main.html', {'form': form})

def save_sportspeople_data(data):
    folder_path = os.path.join(settings.BASE_DIR, 'Sportspeople')  # создаём путь для папки с json
    os.makedirs(folder_path, exist_ok=True)  # создаём папку, если её нет

    file_path = os.path.join(folder_path, 'sportspeople.json')  # если файл существует, формируем путь до него
    if not os.path.exists(file_path):
        with open(file_path, 'w') as f:
            json.dump([], f)  # если файла нет, создаём его как список

    with open(file_path, 'r+') as f:  # открываем файл json
        file_content = f.read().strip()  # чтение без пробелов
        if file_content:  # если файл не пуст (иначе при пустом файле будет выдавать ошибку декодирования)
            f.seek(0)  # возвращаем курсор в начало файла
            sportspeople = json.load(f)  # загружаем данные из файла в переменную
        else:
            sportspeople = []  # если файл пустой, добавляем пустой список
        sportspeople.append(data)  # добавляем в список данные, полученные как аргумент
        f.seek(0)  # переносим курсор в начало строки
        json.dump(sportspeople, f, ensure_ascii=False, indent=4)  # добавляем информацию из переменной в файл f
        
def sportperson_list(request):
    sportspeople = []  # Инициализируем переменную перед использованием
    if request.method == 'POST':
        form = SportListForm(request.POST)
        if form.is_valid():
            readpl = form.cleaned_data['readpl']
            if readpl == '1':
                file_path = os.path.join(settings.BASE_DIR, 'Sportspeople', 'sportspeople.json')
                if os.path.exists(file_path):
                    with open(file_path, 'r') as f:
                        file_content = f.read().strip()
                        if file_content:
                            f.seek(0)
                            sportspeople = json.load(f)
                        else:
                            sportspeople = []
            elif readpl == '2':
                sportspeople = list(Sportspeople.objects.all().values())
            return render(request, 'lab_4/sportperson_list.html', {'sportspeople': sportspeople, 'form': form, 'readpl': readpl})
    else:
        form = SportListForm()
        sportspeople = []
    return render(request, 'lab_4/sportperson_list.html', {'sportspeople': sportspeople, 'form': form})

def upload_file(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('file_list')
    else:
        form = DocumentForm()
    return render(request, 'lab_4/upload.html', {'form': form})

def file_list(request):
    file_dir = os.path.join(settings.MEDIA_ROOT, 'documents')
    json_files = []

    if os.path.exists(file_dir):
        for filename in os.listdir(file_dir):
            if filename.endswith('.json'):
                json_files.append(filename)
    context = {
        'json_files': json_files, #нужен как словарь для html (списки не пропускает)
    }
    return render(request, 'lab_4/file_list.html', context)


def get_sportperson(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            sportperson = list(Sportspeople.objects.all().values())
            return JsonResponse({'context': sportperson})
        return JsonResponse({'status': 'Invalid request'}, status=400)
    else:
       return HttpResponseBadRequest('Invalid request')

def find_sportperson(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            query = request.GET.get('q', '').strip()#получаем строку, ищем значение q
            if query:
                sportperson = list(
                    Sportspeople.objects.filter(name__icontains=query).values() | 
                    Sportspeople.objects.filter(surname__icontains=query).values()
                    ) #Проверка, включают ли поля формы введённую строку   
            else:
                sportperson = list(Sportspeople.objects.all().values())#если ничего не введено, вывести все записи
            return JsonResponse({'context': sportperson})
    return JsonResponse({'status': 'Invalid request'}, status=400)

#функция для редактирования

def edit_sp_temp(request):
    return render(request, 'lab_4/edit_sportperson.html')

def edit_sportperson(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            record_id = request.GET.get('id', '').strip()
            new_spcat = request.GET.get('input', '').strip()
            if record_id and new_spcat:
                s = ".,:;!_*-+()/#%&"
                for char in s:
                    if char in new_spcat:
                        return JsonResponse({'status': 'Incorrect sport category'}, status=400) 
                sportperson = Sportspeople.objects.filter(pk=record_id).update(spcat=new_spcat)
                sportperson = Sportspeople.objects.get(pk=record_id)
                sportperson_data = {
                        'id': sportperson.pk,
                        'name': sportperson.name,
                        'surname': sportperson.surname,
                        'age': sportperson.age,
                        'gender': sportperson.gender,
                        'spcat': sportperson.spcat,
                        'sptype': sportperson.sptype,
                    }
                return JsonResponse({'status': 'Success', 'sportperson': sportperson_data})
    return JsonResponse({'status': 'Invalid request'}, status=400)
                
def delete_sportperson(request):
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            record_id = request.GET.get('id', '').strip()
            if record_id:
                sportperson = get_object_or_404(Sportspeople, pk=record_id)
                sportperson.delete()
                sportperson = list(Sportspeople.objects.all().values())
                return JsonResponse({'status': 'Success', 'context': sportperson})
    return JsonResponse({'status': 'Invalid request'}, status=400)   


#def edit_sportperson(request, pk):
#    sportsperson = get_object_or_404(Sportspeople, pk=pk)
#    
    # Передаем только спортивную категорию для редактирования
#   if request.method == 'POST':
#        form = SportForm(request.POST, instance=sportsperson)
#        
#        if form.is_valid():
#            # Сохраняем только изменение спортивной категории
#            form.save()
#            messages.success(request, 'Спортивная категория успешно обновлена.')
#            return redirect('sportperson_list')  # Перенаправляем на список спортсменов
#    else:
#        form = SportForm(instance=sportsperson)
#
#    return render(request, 'lab_4/edit_sportperson.html', {'form': form})

#def get_sportperson_for_updating(request, id):
#    sportperson = get_object_or_404(Sportspeople, id=id)
#    return JsonResponse({
#        'name': sportperson.name,
#        'surname': sportperson.surname,
#        'age': sportperson.age,
#        'gender': sportperson.gender,
#        'spcat': sportperson.spcat,
#        'sptype': sportperson.sptype,
#    })

lab_4/templates/lab_4/edit_sportperson.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактировать спортсмена</title>
</head>
<body>
    <h1>Редактировать спортивную категорию</h1>
    <div id="error-message" style="color: red; display: none;"></div>
    <div id="button_print_all_db">
        <button class="btn btn-primary">Вывести записи из БД</button>
    </div>
    <h1>Sportsperson List</h1>
        <table id="sport-table" border="1">
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Sport Category</th>
                <th>Sport Types</th>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table> <br>
        <a href="{% url 'splist' %}">Вернуться на страницу просмотра содержимого</a>
    <script>
        document.addEventListener('DOMContentLoaded', function() 
        {
            const Button_print = document.getElementById('button_print_all_db');
            const GetSportUrls = "{% url 'get_sportperson' %}";
            Button_print.addEventListener('click', function() //слушаем изменение поля инпут
            {
                getAllSportperson(GetSportUrls);
            });
        })
        document.addEventListener('DOMContentLoaded', function() 
        {
            const Button_edit = document.getElementById('button_edit_db');
        })
        function StartEdit(obj)
        {
            
            const edit_url = "{% url 'edit_sportperson' %}";
            const id_button = obj.id;
            const id_spcat = obj.id;
            const input_spcat = document.getElementById(`spcat-${id_button}`).value;
            edit_sportperson(edit_url, id_button, input_spcat);
        }
        function StartDelete(obj)
        {
            const delete_url = "{% url 'delete_sportperson' %}";
            const id_button = obj.id;
            delete_sportperson(delete_url, id_button);
        }
    </script>
    <script src="{% static 'lab_4/js/main.js' %}"></script>
</body>
</html>

lab_4/templates/lab_4/file_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Загруженные файлы</h2>
        {% if no_files %}
            <p>No JSON files found.</p>
        {% else %}
    <h3>JSON файлы:</h3>
        <ul>
            {% for file in json_files %}
                <li>{{ file }}</li>
            {% endfor %}
        </ul>  
        {% endif %}
        <a href="{% url 'sport_view' %}">Вернуться на главную</a>
</body>
</html>

lab_4/templates/lab_4/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="f">
            <label for="id_name">{{ form.name.label }}</label>
            {{ form.name }}
        </div>
        <div class="f">
            <label for="id_surname">{{ form.surname.label }}</label>
            {{ form.surname }}
        </div>
        <div class="f">
            <label for="id_age">{{ form.age.label }}</label>
            {{ form.age }}
            {% if form.age.errors %}
                <div class="error">{{ form.age.errors }}</div> <!-- Если произошла ошибка -->
            {% endif %}
        </div>
        <div class="f">
            <label for="id_gender">{{ form.gender.label }}</label>
            {{ form.gender }}
        </div>
        <div class="f">
            <label for="id_cats">{{ form.spcat.label }}</label>
            {{ form.spcat }}
        </div>
        <div class="f">
            <label for="id_types">{{ form.sptype.label }}</label>
            {{ form.sptype }}
            {% if form.sptype.errors %}
                <div class="error">{{ form.sptype.errors }}</div> <!-- Если произошла ошибка (не выбран ни один вариант)-->
            {% endif %}
        </div>
        <div class="f">
            <label for="id_save">{{ form.savepl.label }}</label>
            {{ form.savepl }}
        </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
    </form>

    <a href="{% url 'upload_file' %}">Перейти на страницу загрузки файлов</a><br>
    <a href="{% url 'splist' %}">Перейти на страницу просмотра содержимого</a>
</div>
</body>
</html>

lab_4/templates/lab_4/sportperson_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<body>
    {% if form.readpl.value == '1' %}
        <h1>СЕЙЧАС ВЫБРАН JSON</h1>
    {% else %}
        <h1>СЕЙЧАС ВЫБРАНА БД</h1>
    {% endif %}
    <div>
        <form method="post">
            {% csrf_token %}
            <div class="f">
                <label for="id_read">{{ form.readpl.label }}</label>
                {{ form.readpl }}
            </div>
            <button type="submit" class="btn btn-primary">Выбрать</button>
        </form>
    </div>
    <div>
        {% if form.readpl.value == '1' %}
            <div id="button_print_all_json">
                <button class="btn btn-primary">Вывести всё из JSON</button>
            </div>
        {% else %}
            <div id="button_print_all_db">
                <button class="btn btn-primary">Вывести всё из БД</button>
            </div>
            <div>
                <div>
                    <input type="text" id="search-input" placeholder="Введите имя или фамилию для поиска...">
                    <button id="search-button">Поиск</button>
                </div>
            </div>
        {% endif %}
        <h1>Sportsperson List</h1>
        <table id="sport-table" border="1">
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Sport Category</th>
                <th>Sport Types</th>
            </tr>
            {% if form.readpl.value == '1' %}
                {% for person in sportspeople %}
                <tr>
                    <td id="name">{{ person.name }}</td>
                    <td id="surname">{{ person.surname }}</td>
                    <td id="age">{{ person.age }}</td>
                    <td id="gender">{{ person.gender }}</td>
                    <td id="spcat">{{ person.spcat }}</td>
                    <td id="sptype">{{ person.sptype }}</td>
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            {% endif %}
        </table> <br>

        <div class="editing">
        </div> <br>
        <div class="deleting">
            <td><button class="delete-button" data-id="{{ person.id }}">Удалить</button></td>
        </div>
    </div>
    <a href="{% url 'sport_view' %}">Вернуться на главную</a><br>
    <a href="{% url 'edit_sp_temp' %}">Перейти на страницу редактирования и удаления</a>
    <script>
        document.addEventListener('DOMContentLoaded', function() 
        {
            const Button_print = document.getElementById('button_print_all_db');
            const outputField = document.getElementById('search-results');
            const GetSportUrls = "{% url 'get_sportperson' %}";
            Button_print.addEventListener('click', function() //слушаем изменение поля инпут
            {
                getAllSportperson(GetSportUrls);
            });
            const Button_print_JSON = document.getElementById('button_print_all_json');
            Button_print_JSON.addEventListener('click', function()
            {
                const data = JSON.parse('D:/my_app/Sportspeople/sportspeople.json')
                console.log(data)
                fetch('D:/my_app/Sportspeople/sportspeople.json')
                .then(response => {
                if (!response.ok) 
                {
                    throw new Error('Ой, ошибка в fetch: ' + response.statusText);
                }
                return response.json();
                })
                .then(jsonData => console.log(jsonData))
                .catch(error => console.error('Ошибка при исполнении запроса: ', error));
            });
        });

        //для поиска
        const searchUrl = "{% url 'find_sportperson' %}";
        document.getElementById("search-button").addEventListener("click", () => 
        {
            const query = document.getElementById("search-input").value;
            searchSportspeople(searchUrl, query);
        });

    </script>
    <script src="{% static 'lab_4/js/main.js' %}"></script>
</body>
</html>

lab_4/templates/lab_4/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" enctype="multipart/form-data"> <!-- Для отправления файла вместе с формой-->
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Загрузить</button>
    </form>    
</body>
</html>